apiVersion: v1
kind: ConfigMap
metadata:
  name: sales-aggregator-config
  labels:
    {{- include "sales-aggregator.labels" . | nindent 4 }}
data:
  DJANGO_DEBUG: "0"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,sales-aggregator"
