apiVersion: v1
kind: Secret
metadata:
  name: sales-aggregator-secrets
  labels:
    {{- include "sales-aggregator.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.database.url | quote }}
  django-secret-key: django-insecure-lab6-sales-aggregator-secret
