apiVersion: v1
kind: Service
metadata:
  name: sales-aggregator
  labels:
    {{- include "sales-aggregator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.app.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sales-aggregator.selectorLabels" . | nindent 4 }}
