apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sales-demo

bases:
  - ../../base

patches:
  - path: patch-statefulset.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: postgres

secretGenerator:
  - name: postgres-credentials
    literals:
      - username=postgres
      - password=postgres
      - database=sales_db
    options:
      disableNameSuffixHash: true

commonLabels:
  environment: dev
