fullnameOverride: postgres

image:
  repository: postgres
  tag: "15-alpine"
  pullPolicy: IfNotPresent

auth:
  username: postgres
  database: sales_db

password: "changeme"

persistence:
  enabled: true
  size: 2Gi
  storageClass: ""

service:
  port: 5432

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

podLabels: {}
podAnnotations: {}
