apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-infra.fullname" . }}-credentials
  labels:
    {{- include "postgres-infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username }}
  database: {{ .Values.auth.database }}
  postgres-password: {{ .Values.password }}
