apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-infra.fullname" . }}
  labels:
    {{- include "postgres-infra.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      name: postgres
  selector:
    {{- include "postgres-infra.selectorLabels" . | nindent 4 }}
