# Generated by Django 5.2.7 on 2025-11-07 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
